// GENERADO por backend/scripts/geografia/gen_catalogo.mjs — NO editar a mano.
//
// Paises: 232 (ISO-3166 alfa-2 derivado del CLDR de Node; 1 inactivo por
// codigo retirado). Provincias: 24. Cantones: 221. Los dos ultimos, del
// Clasificador Geografico Estadistico 2025 del INEC.
//
// La unicidad de un canton es (provincia, nombre), NUNCA el nombre: "Bolivar" y "Olmedo"
// existen en dos provincias distintas cada uno.

export const PAISES = [
  {"iso":"AF","nombre":"Afganistán","nombre_en":"Afghanistan","prefijo":"+93","activo":1},
  {"iso":"AL","nombre":"Albania","nombre_en":"Albania","prefijo":"+355","activo":1},
  {"iso":"DZ","nombre":"Algeria","nombre_en":"Algeria","prefijo":"+213","activo":1},
  {"iso":"AS","nombre":"Samoa Americana","nombre_en":"American Samoa","prefijo":"+1-684","activo":1},
  {"iso":"AD","nombre":"Andorra","nombre_en":"Andorra","prefijo":"+376","activo":1},
  {"iso":"AO","nombre":"Angola","nombre_en":"Angola","prefijo":"+244","activo":1},
  {"iso":"AI","nombre":"Anguilla","nombre_en":"Anguilla","prefijo":"+1-264","activo":1},
  {"iso":"AQ","nombre":"Antártida","nombre_en":"Antarctica","prefijo":"+672","activo":1},
  {"iso":"AG","nombre":"Antigua y Barbuda","nombre_en":"Antigua and Barbuda","prefijo":"+1-268","activo":1},
  {"iso":"AR","nombre":"Argentina","nombre_en":"Argentina","prefijo":"+54","activo":1},
  {"iso":"AM","nombre":"Armenia","nombre_en":"Armenia","prefijo":"+374","activo":1},
  {"iso":"AW","nombre":"Aruba","nombre_en":"Aruba","prefijo":"+297","activo":1},
  {"iso":"AU","nombre":"Australia","nombre_en":"Australia","prefijo":"+61","activo":1},
  {"iso":"AT","nombre":"Austria","nombre_en":"Austria","prefijo":"+43","activo":1},
  {"iso":"AZ","nombre":"Azerbaiyán","nombre_en":"Azerbaijan","prefijo":"+994","activo":1},
  {"iso":"BS","nombre":"Bahamas","nombre_en":"Bahamas","prefijo":"+1-242","activo":1},
  {"iso":"BH","nombre":"Bahrein","nombre_en":"Bahrain","prefijo":"+973","activo":1},
  {"iso":"BD","nombre":"Bangladesh","nombre_en":"Bangladesh","prefijo":"+880","activo":1},
  {"iso":"BB","nombre":"Barbados","nombre_en":"Barbados","prefijo":"+1-246","activo":1},
  {"iso":"BY","nombre":"Bielorrusia","nombre_en":"Belarus","prefijo":"+375","activo":1},
  {"iso":"BE","nombre":"Bélgica","nombre_en":"Belgium","prefijo":"+32","activo":1},
  {"iso":"BZ","nombre":"Belice","nombre_en":"Belize","prefijo":"+501","activo":1},
  {"iso":"BJ","nombre":"Benín","nombre_en":"Benin","prefijo":"+229","activo":1},
  {"iso":"BM","nombre":"Bermuda","nombre_en":"Bermuda","prefijo":"+1-441","activo":1},
  {"iso":"BT","nombre":"Bután","nombre_en":"Bhutan","prefijo":"+975","activo":1},
  {"iso":"BO","nombre":"Bolivia","nombre_en":"Bolivia","prefijo":"+591","activo":1},
  {"iso":"BA","nombre":"Bosnia-Herzegovina","nombre_en":"Bosnia and Herzegovina","prefijo":"+387","activo":1},
  {"iso":"BW","nombre":"Botswana","nombre_en":"Botswana","prefijo":"+267","activo":1},
  {"iso":"BR","nombre":"Brasil","nombre_en":"Brazil","prefijo":"+55","activo":1},
  {"iso":"BN","nombre":"Brunei","nombre_en":"Brunei Darussalam","prefijo":"+673","activo":1},
  {"iso":"BG","nombre":"Bulgaria","nombre_en":"Bulgaria","prefijo":"+359","activo":1},
  {"iso":"BF","nombre":"Burkina Faso","nombre_en":"Burkina Faso","prefijo":"+226","activo":1},
  {"iso":"BI","nombre":"Burundi","nombre_en":"Burundi","prefijo":"+257","activo":1},
  {"iso":"KH","nombre":"Camboya","nombre_en":"Cambodia","prefijo":"+855","activo":1},
  {"iso":"CM","nombre":"Camerún","nombre_en":"Cameroon","prefijo":"+237","activo":1},
  {"iso":"CA","nombre":"Canadá","nombre_en":"Canada","prefijo":"+1","activo":1},
  {"iso":"CV","nombre":"Cabo Verde","nombre_en":"Cape Verde","prefijo":"+238","activo":1},
  {"iso":"KY","nombre":"Islas Caimán","nombre_en":"Cayman Islands","prefijo":"+1-345","activo":1},
  {"iso":"CF","nombre":"República Centroafricana","nombre_en":"Central African Republic","prefijo":"+236","activo":1},
  {"iso":"TD","nombre":"Chad","nombre_en":"Chad","prefijo":"+235","activo":1},
  {"iso":"CL","nombre":"Chile","nombre_en":"Chile","prefijo":"+56","activo":1},
  {"iso":"CN","nombre":"China","nombre_en":"China","prefijo":"+86","activo":1},
  {"iso":"CX","nombre":"Isla de Navidad","nombre_en":"Christmas Island","prefijo":"+61","activo":1},
  {"iso":"CC","nombre":"Islas Cocos","nombre_en":"Cocos (Keeling) Islands","prefijo":"+61","activo":1},
  {"iso":"CO","nombre":"Colombia","nombre_en":"Colombia","prefijo":"+57","activo":1},
  {"iso":"KM","nombre":"Comores","nombre_en":"Comoros","prefijo":"+269","activo":1},
  {"iso":"CG","nombre":"República del Congo","nombre_en":"Congo","prefijo":"+242","activo":1},
  {"iso":"CD","nombre":"República Democrática del Congo","nombre_en":"Congo, The Democratic Republic of the","prefijo":"+243","activo":1},
  {"iso":"CK","nombre":"Islas Cook","nombre_en":"Cook Islands","prefijo":"+682","activo":1},
  {"iso":"CR","nombre":"Costa Rica","nombre_en":"Costa Rica","prefijo":"+506","activo":1},
  {"iso":"CI","nombre":"Costa de Marfíl","nombre_en":"Cote D'Ivoire","prefijo":"+225","activo":1},
  {"iso":"HR","nombre":"Croacia","nombre_en":"Croatia","prefijo":"+385","activo":1},
  {"iso":"CU","nombre":"Cuba","nombre_en":"Cuba","prefijo":"+53","activo":1},
  {"iso":"CY","nombre":"Chipre","nombre_en":"Cyprus","prefijo":"+357","activo":1},
  {"iso":"CZ","nombre":"República Checa","nombre_en":"Czech Republic","prefijo":"+420","activo":1},
  {"iso":"DK","nombre":"Dinamarca","nombre_en":"Denmark","prefijo":"+45","activo":1},
  {"iso":"DJ","nombre":"Djibouti","nombre_en":"Djibouti","prefijo":"+253","activo":1},
  {"iso":"DM","nombre":"Dominica","nombre_en":"Dominica","prefijo":"+1-767","activo":1},
  {"iso":"DO","nombre":"República Dominicana","nombre_en":"Dominican Republic","prefijo":"+1-809","activo":1},
  {"iso":"EC","nombre":"Ecuador","nombre_en":"Ecuador","prefijo":"+593","activo":1},
  {"iso":"EG","nombre":"Egipto","nombre_en":"Egypt","prefijo":"+20","activo":1},
  {"iso":"SV","nombre":"El Salvador","nombre_en":"El Salvador","prefijo":"+503","activo":1},
  {"iso":"GQ","nombre":"Guinea Ecuatorial","nombre_en":"Equatorial Guinea","prefijo":"+240","activo":1},
  {"iso":"ER","nombre":"Eritrea","nombre_en":"Eritrea","prefijo":"+291","activo":1},
  {"iso":"EE","nombre":"Estonia","nombre_en":"Estonia","prefijo":"+372","activo":1},
  {"iso":"ET","nombre":"Etiopía","nombre_en":"Ethiopia","prefijo":"+251","activo":1},
  {"iso":"FK","nombre":"Islas Malvinas","nombre_en":"Falkland Islands (Malvinas)","prefijo":"+500","activo":1},
  {"iso":"FO","nombre":"Islas Feroe","nombre_en":"Faroe Islands","prefijo":"+298","activo":1},
  {"iso":"FJ","nombre":"Fiji","nombre_en":"Fiji","prefijo":"+679","activo":1},
  {"iso":"FI","nombre":"Finlandia","nombre_en":"Finland","prefijo":"+358","activo":1},
  {"iso":"FR","nombre":"Francia","nombre_en":"France","prefijo":"+33","activo":1},
  {"iso":"GF","nombre":"Guyana Francesa","nombre_en":"French Guiana","prefijo":"+594","activo":1},
  {"iso":"PF","nombre":"Polinesia Francesa","nombre_en":"French Polynesia","prefijo":"+689","activo":1},
  {"iso":"TF","nombre":"Tierras Australes y Antárticas Francesas","nombre_en":"French Southern Territories","prefijo":"+262","activo":1},
  {"iso":"GA","nombre":"Gabón","nombre_en":"Gabon","prefijo":"+241","activo":1},
  {"iso":"GM","nombre":"Gambia","nombre_en":"Gambia","prefijo":"+220","activo":1},
  {"iso":"GE","nombre":"Georgia","nombre_en":"Georgia","prefijo":"+995","activo":1},
  {"iso":"DD","nombre":"Alemania","nombre_en":"Germany","prefijo":"+49","activo":1},
  {"iso":"GH","nombre":"Ghana","nombre_en":"Ghana","prefijo":"+233","activo":1},
  {"iso":"GI","nombre":"Gibraltar","nombre_en":"Gibraltar","prefijo":"+350","activo":1},
  {"iso":"GR","nombre":"Grecia","nombre_en":"Greece","prefijo":"+30","activo":1},
  {"iso":"GL","nombre":"Groenlandia","nombre_en":"Greenland","prefijo":"+299","activo":1},
  {"iso":"GD","nombre":"Granada","nombre_en":"Grenada","prefijo":"+1-473","activo":1},
  {"iso":"GP","nombre":"Guadalupe","nombre_en":"Guadeloupe","prefijo":"+590","activo":1},
  {"iso":"GU","nombre":"Guam","nombre_en":"Guam","prefijo":"+1-671","activo":1},
  {"iso":"GT","nombre":"Guatemala","nombre_en":"Guatemala","prefijo":"+502","activo":1},
  {"iso":"GN","nombre":"Guinea","nombre_en":"Guinea","prefijo":"+224","activo":1},
  {"iso":"GW","nombre":"Guinea-Bissau","nombre_en":"Guinea-Bissau","prefijo":"+245","activo":1},
  {"iso":"GY","nombre":"Guyana","nombre_en":"Guyana","prefijo":"+592","activo":1},
  {"iso":"HT","nombre":"Haití","nombre_en":"Haiti","prefijo":"+509","activo":1},
  {"iso":"VA","nombre":"Vaticano","nombre_en":"Holy See (Vatican City State)","prefijo":"+379","activo":1},
  {"iso":"HN","nombre":"Honduras","nombre_en":"Honduras","prefijo":"+504","activo":1},
  {"iso":"HK","nombre":"Hong Kong","nombre_en":"Hong Kong","prefijo":"+852","activo":1},
  {"iso":"HU","nombre":"Hungría","nombre_en":"Hungary","prefijo":"+36","activo":1},
  {"iso":"IS","nombre":"Islandia","nombre_en":"Iceland","prefijo":"+354","activo":1},
  {"iso":"IN","nombre":"India","nombre_en":"India","prefijo":"+91","activo":1},
  {"iso":"ID","nombre":"Indonesia","nombre_en":"Indonesia","prefijo":"+62","activo":1},
  {"iso":"IR","nombre":"Irán","nombre_en":"Iran, Islamic Republic Of","prefijo":"+98","activo":1},
  {"iso":"IQ","nombre":"Iraq","nombre_en":"Iraq","prefijo":"+964","activo":1},
  {"iso":"IE","nombre":"Irlanda","nombre_en":"Ireland","prefijo":"+353","activo":1},
  {"iso":"IL","nombre":"Israel","nombre_en":"Israel","prefijo":"+972","activo":1},
  {"iso":"IT","nombre":"Italia","nombre_en":"Italy","prefijo":"+39","activo":1},
  {"iso":"JM","nombre":"Jamaica","nombre_en":"Jamaica","prefijo":"+1-876","activo":1},
  {"iso":"JP","nombre":"Japón","nombre_en":"Japan","prefijo":"+81","activo":1},
  {"iso":"JO","nombre":"Jordania","nombre_en":"Jordan","prefijo":"+962","activo":1},
  {"iso":"KZ","nombre":"Kazajstán","nombre_en":"Kazakhstan","prefijo":"+7","activo":1},
  {"iso":"KE","nombre":"Kenia","nombre_en":"Kenya","prefijo":"+254","activo":1},
  {"iso":"KI","nombre":"Kiribati","nombre_en":"Kiribati","prefijo":"+686","activo":1},
  {"iso":"KP","nombre":"Corea del Norte","nombre_en":"Korea, Democratic People'S Republic of","prefijo":"+850","activo":1},
  {"iso":"KR","nombre":"Corea del Sur","nombre_en":"Korea, Republic of","prefijo":"+82","activo":1},
  {"iso":"KW","nombre":"Kuwait","nombre_en":"Kuwait","prefijo":"+965","activo":1},
  {"iso":"KG","nombre":"Kirguistán","nombre_en":"Kyrgyzstan","prefijo":"+996","activo":1},
  {"iso":"LA","nombre":"Laos","nombre_en":"Lao People's Democratic Republic","prefijo":"+856","activo":1},
  {"iso":"LV","nombre":"Letonia","nombre_en":"Latvia","prefijo":"+371","activo":1},
  {"iso":"LB","nombre":"Líbano","nombre_en":"Lebanon","prefijo":"+961","activo":1},
  {"iso":"LS","nombre":"Lesotho","nombre_en":"Lesotho","prefijo":"+266","activo":1},
  {"iso":"LR","nombre":"Liberia","nombre_en":"Liberia","prefijo":"+231","activo":1},
  {"iso":"LY","nombre":"Libia","nombre_en":"Libyan Arab Jamahiriya","prefijo":"+218","activo":1},
  {"iso":"LI","nombre":"Liechtenstein","nombre_en":"Liechtenstein","prefijo":"+423","activo":1},
  {"iso":"LT","nombre":"Lituania","nombre_en":"Lithuania","prefijo":"+370","activo":1},
  {"iso":"LU","nombre":"Luxemburgo","nombre_en":"Luxembourg","prefijo":"+352","activo":1},
  {"iso":"MO","nombre":"Macao","nombre_en":"Macao","prefijo":"+853","activo":1},
  {"iso":"MK","nombre":"Macedonia","nombre_en":"Macedonia, The Former Yugoslav Republic of","prefijo":"+389","activo":1},
  {"iso":"MG","nombre":"Madagascar","nombre_en":"Madagascar","prefijo":"+261","activo":1},
  {"iso":"MW","nombre":"Malawi","nombre_en":"Malawi","prefijo":"+265","activo":1},
  {"iso":"MY","nombre":"Malasia","nombre_en":"Malaysia","prefijo":"+60","activo":1},
  {"iso":"MV","nombre":"Maldivas","nombre_en":"Maldives","prefijo":"+960","activo":1},
  {"iso":"ML","nombre":"Mali","nombre_en":"Mali","prefijo":"+223","activo":1},
  {"iso":"MT","nombre":"Malta","nombre_en":"Malta","prefijo":"+356","activo":1},
  {"iso":"MH","nombre":"Islas Marshall","nombre_en":"Marshall Islands","prefijo":"+692","activo":1},
  {"iso":"MQ","nombre":"Martinica","nombre_en":"Martinique","prefijo":"+596","activo":1},
  {"iso":"MR","nombre":"Mauritania","nombre_en":"Mauritania","prefijo":"+222","activo":1},
  {"iso":"MU","nombre":"Mauricio","nombre_en":"Mauritius","prefijo":"+230","activo":1},
  {"iso":"YT","nombre":"Mayotte","nombre_en":"Mayotte","prefijo":"+262","activo":1},
  {"iso":"MX","nombre":"México","nombre_en":"Mexico","prefijo":"+52","activo":1},
  {"iso":"FM","nombre":"Estados Federados de Micronesia","nombre_en":"Micronesia, Federated States of","prefijo":"+691","activo":1},
  {"iso":"MD","nombre":"Moldavia","nombre_en":"Moldova, Republic of","prefijo":"+373","activo":1},
  {"iso":"MC","nombre":"Mónaco","nombre_en":"Monaco","prefijo":"+377","activo":1},
  {"iso":"MN","nombre":"Mongolia","nombre_en":"Mongolia","prefijo":"+976","activo":1},
  {"iso":"MS","nombre":"Montserrat","nombre_en":"Montserrat","prefijo":"+1-664","activo":1},
  {"iso":"MA","nombre":"Marruecos","nombre_en":"Morocco","prefijo":"+212","activo":1},
  {"iso":"MZ","nombre":"Mozambique","nombre_en":"Mozambique","prefijo":"+258","activo":1},
  {"iso":"MM","nombre":"Myanmar","nombre_en":"Myanmar","prefijo":"+95","activo":1},
  {"iso":"NA","nombre":"Namibia","nombre_en":"Namibia","prefijo":"+264","activo":1},
  {"iso":"NR","nombre":"Nauru","nombre_en":"Nauru","prefijo":"+674","activo":1},
  {"iso":"NP","nombre":"Nepal","nombre_en":"Nepal","prefijo":"+977","activo":1},
  {"iso":"NL","nombre":"Holanda","nombre_en":"Netherlands","prefijo":"+31","activo":1},
  {"iso":"AN","nombre":"Antillas Holandesas","nombre_en":"Netherlands Antilles","prefijo":"+599","activo":0},
  {"iso":"NC","nombre":"Nueva Caledonia","nombre_en":"New Caledonia","prefijo":"+687","activo":1},
  {"iso":"NZ","nombre":"Nueva Zelanda","nombre_en":"New Zealand","prefijo":"+64","activo":1},
  {"iso":"NI","nombre":"Nicaragua","nombre_en":"Nicaragua","prefijo":"+505","activo":1},
  {"iso":"NE","nombre":"Niger","nombre_en":"Niger","prefijo":"+227","activo":1},
  {"iso":"NG","nombre":"Nigeria","nombre_en":"Nigeria","prefijo":"+234","activo":1},
  {"iso":"NU","nombre":"Niue","nombre_en":"Niue","prefijo":"+683","activo":1},
  {"iso":"NF","nombre":"Islas Norfolk","nombre_en":"Norfolk Island","prefijo":"+672","activo":1},
  {"iso":"MP","nombre":"Islas Marianas del Norte","nombre_en":"Northern Mariana Islands","prefijo":"+1-670","activo":1},
  {"iso":"NO","nombre":"Noruega","nombre_en":"Norway","prefijo":"+47","activo":1},
  {"iso":"OM","nombre":"Omán","nombre_en":"Oman","prefijo":"+968","activo":1},
  {"iso":"PK","nombre":"Pakistán","nombre_en":"Pakistan","prefijo":"+92","activo":1},
  {"iso":"PW","nombre":"Palau","nombre_en":"Palau","prefijo":"+680","activo":1},
  {"iso":"PS","nombre":"Palestina","nombre_en":"Palestinian Territory, Occupied","prefijo":"+970","activo":1},
  {"iso":"PA","nombre":"Panamá","nombre_en":"Panama","prefijo":"+507","activo":1},
  {"iso":"PG","nombre":"Papua Nueva Guinea","nombre_en":"Papua New Guinea","prefijo":"+675","activo":1},
  {"iso":"PY","nombre":"Paraguay","nombre_en":"Paraguay","prefijo":"+595","activo":1},
  {"iso":"PE","nombre":"Perú","nombre_en":"Peru","prefijo":"+51","activo":1},
  {"iso":"PH","nombre":"Filipinas","nombre_en":"Philippines","prefijo":"+63","activo":1},
  {"iso":"PN","nombre":"Pitcairn","nombre_en":"Pitcairn","prefijo":"+64","activo":1},
  {"iso":"PL","nombre":"Polonia","nombre_en":"Poland","prefijo":"+48","activo":1},
  {"iso":"PT","nombre":"Portugal","nombre_en":"Portugal","prefijo":"+351","activo":1},
  {"iso":"PR","nombre":"Puerto Rico","nombre_en":"Puerto Rico","prefijo":"+1-787","activo":1},
  {"iso":"QA","nombre":"Qatar","nombre_en":"Qatar","prefijo":"+974","activo":1},
  {"iso":"RE","nombre":"Reunión","nombre_en":"Reunion","prefijo":"+262","activo":1},
  {"iso":"RO","nombre":"Rumanía","nombre_en":"Romania","prefijo":"+40","activo":1},
  {"iso":"RU","nombre":"Rusia","nombre_en":"Russian Federation","prefijo":"+7","activo":1},
  {"iso":"RW","nombre":"Ruanda","nombre_en":"Rwanda","prefijo":"+250","activo":1},
  {"iso":"SH","nombre":"Santa Helena","nombre_en":"Saint Helena","prefijo":"+290","activo":1},
  {"iso":"KN","nombre":"San Kitts y Nevis","nombre_en":"Saint Kitts and Nevis","prefijo":"+1-869","activo":1},
  {"iso":"LC","nombre":"Santa Lucía","nombre_en":"Saint Lucia","prefijo":"+1-758","activo":1},
  {"iso":"VC","nombre":"San Vicente y Granadinas","nombre_en":"Saint Vincent and the Grenadines","prefijo":"+1-784","activo":1},
  {"iso":"WS","nombre":"Samoa","nombre_en":"Samoa","prefijo":"+685","activo":1},
  {"iso":"SM","nombre":"San Marino","nombre_en":"San Marino","prefijo":"+378","activo":1},
  {"iso":"ST","nombre":"Santo Tomé y Príncipe","nombre_en":"Sao Tome and Principe","prefijo":"+239","activo":1},
  {"iso":"SA","nombre":"Arabia Saudita","nombre_en":"Saudi Arabia","prefijo":"+966","activo":1},
  {"iso":"SN","nombre":"Senegal","nombre_en":"Senegal","prefijo":"+221","activo":1},
  {"iso":"CS","nombre":"Serbia","nombre_en":"Serbia and Montenegro","prefijo":"+381","activo":1},
  {"iso":"SC","nombre":"Seychelles","nombre_en":"Seychelles","prefijo":"+248","activo":1},
  {"iso":"SL","nombre":"Sierra Leona","nombre_en":"Sierra Leone","prefijo":"+232","activo":1},
  {"iso":"SG","nombre":"Singapur","nombre_en":"Singapore","prefijo":"+65","activo":1},
  {"iso":"SK","nombre":"Eslovaquía","nombre_en":"Slovakia","prefijo":"+421","activo":1},
  {"iso":"SI","nombre":"Eslovenia","nombre_en":"Slovenia","prefijo":"+386","activo":1},
  {"iso":"SB","nombre":"Islas Salomón","nombre_en":"Solomon Islands","prefijo":"+677","activo":1},
  {"iso":"SO","nombre":"Somalia","nombre_en":"Somalia","prefijo":"+252","activo":1},
  {"iso":"ZA","nombre":"Sudáfrica","nombre_en":"South Africa","prefijo":"+27","activo":1},
  {"iso":"ES","nombre":"España","nombre_en":"Spain","prefijo":"+34","activo":1},
  {"iso":"LK","nombre":"Sri Lanka","nombre_en":"Sri Lanka","prefijo":"+94","activo":1},
  {"iso":"SD","nombre":"Sudán","nombre_en":"Sudan","prefijo":"+249","activo":1},
  {"iso":"SR","nombre":"Surinam","nombre_en":"Suriname","prefijo":"+597","activo":1},
  {"iso":"SZ","nombre":"Swazilandia","nombre_en":"Swaziland","prefijo":"+268","activo":1},
  {"iso":"SE","nombre":"Suecia","nombre_en":"Sweden","prefijo":"+46","activo":1},
  {"iso":"CH","nombre":"Suiza","nombre_en":"Switzerland","prefijo":"+41","activo":1},
  {"iso":"SY","nombre":"Siria","nombre_en":"Syrian Arab Republic","prefijo":"+963","activo":1},
  {"iso":"TW","nombre":"Taiwán","nombre_en":"Taiwan, Province of China","prefijo":"+886","activo":1},
  {"iso":"TJ","nombre":"Tadjikistan","nombre_en":"Tajikistan","prefijo":"+992","activo":1},
  {"iso":"TZ","nombre":"Tanzania","nombre_en":"Tanzania, United Republic of","prefijo":"+255","activo":1},
  {"iso":"TH","nombre":"Tailandia","nombre_en":"Thailand","prefijo":"+66","activo":1},
  {"iso":"TL","nombre":"Timor Oriental","nombre_en":"Timor-Leste","prefijo":"+670","activo":1},
  {"iso":"TG","nombre":"Togo","nombre_en":"Togo","prefijo":"+228","activo":1},
  {"iso":"TK","nombre":"Tokelau","nombre_en":"Tokelau","prefijo":"+690","activo":1},
  {"iso":"TO","nombre":"Tonga","nombre_en":"Tonga","prefijo":"+676","activo":1},
  {"iso":"TT","nombre":"Trinidad y Tobago","nombre_en":"Trinidad and Tobago","prefijo":"+1-868","activo":1},
  {"iso":"TN","nombre":"Túnez","nombre_en":"Tunisia","prefijo":"+216","activo":1},
  {"iso":"TR","nombre":"Turquía","nombre_en":"Turkey","prefijo":"+90","activo":1},
  {"iso":"TM","nombre":"Turkmenistan","nombre_en":"Turkmenistan","prefijo":"+993","activo":1},
  {"iso":"TC","nombre":"Islas Turcas y Caicos","nombre_en":"Turks and Caicos Islands","prefijo":"+1-649","activo":1},
  {"iso":"TV","nombre":"Tuvalu","nombre_en":"Tuvalu","prefijo":"+688","activo":1},
  {"iso":"UG","nombre":"Uganda","nombre_en":"Uganda","prefijo":"+256","activo":1},
  {"iso":"UA","nombre":"Ucrania","nombre_en":"Ukraine","prefijo":"+380","activo":1},
  {"iso":"AE","nombre":"Emiratos Árabes Unidos","nombre_en":"United Arab Emirates","prefijo":"+971","activo":1},
  {"iso":"GB","nombre":"Reino Unido","nombre_en":"United Kingdom","prefijo":"+44","activo":1},
  {"iso":"US","nombre":"Estados Unidos","nombre_en":"United States","prefijo":"+1","activo":1},
  {"iso":"UY","nombre":"Uruguay","nombre_en":"Uruguay","prefijo":"+598","activo":1},
  {"iso":"UZ","nombre":"Uzbekistán","nombre_en":"Uzbekistan","prefijo":"+998","activo":1},
  {"iso":"NH","nombre":"Vanuatu","nombre_en":"Vanuatu","prefijo":"+678","activo":1},
  {"iso":"VE","nombre":"Venezuela","nombre_en":"Venezuela","prefijo":"+58","activo":1},
  {"iso":"VD","nombre":"Vietnam","nombre_en":"Viet Nam","prefijo":"+84","activo":1},
  {"iso":"VG","nombre":"Islas Vírgenes Británicas","nombre_en":"Virgin Islands, British","prefijo":"+1-284","activo":1},
  {"iso":"VI","nombre":"Islas Vírgenes Americanas","nombre_en":"Virgin Islands, U.S.","prefijo":"+1-340","activo":1},
  {"iso":"WF","nombre":"Wallis y Futuna","nombre_en":"Wallis and Futuna","prefijo":"+681","activo":1},
  {"iso":"EH","nombre":"Sáhara Occidental","nombre_en":"Western Sahara","prefijo":"+212","activo":1},
  {"iso":"YD","nombre":"Yemen","nombre_en":"Yemen","prefijo":"+967","activo":1},
  {"iso":"ZM","nombre":"Zambia","nombre_en":"Zambia","prefijo":"+260","activo":1},
  {"iso":"RH","nombre":"Zimbabwe","nombre_en":"Zimbabwe","prefijo":"+263","activo":1},
];

export const PROVINCIAS_EC = [
  {"dpa":"01","nombre":"Azuay"},
  {"dpa":"02","nombre":"Bolívar"},
  {"dpa":"03","nombre":"Cañar"},
  {"dpa":"04","nombre":"Carchi"},
  {"dpa":"05","nombre":"Cotopaxi"},
  {"dpa":"06","nombre":"Chimborazo"},
  {"dpa":"07","nombre":"El Oro"},
  {"dpa":"08","nombre":"Esmeraldas"},
  {"dpa":"09","nombre":"Guayas"},
  {"dpa":"10","nombre":"Imbabura"},
  {"dpa":"11","nombre":"Loja"},
  {"dpa":"12","nombre":"Ríos"},
  {"dpa":"13","nombre":"Manabí"},
  {"dpa":"14","nombre":"Morona Santiago"},
  {"dpa":"15","nombre":"Napo"},
  {"dpa":"16","nombre":"Pastaza"},
  {"dpa":"17","nombre":"Pichincha"},
  {"dpa":"18","nombre":"Tungurahua"},
  {"dpa":"19","nombre":"Zamora Chinchipe"},
  {"dpa":"20","nombre":"Galápagos"},
  {"dpa":"21","nombre":"Sucumbíos"},
  {"dpa":"22","nombre":"Orellana"},
  {"dpa":"23","nombre":"Santo Domingo De Los Tsáchilas"},
  {"dpa":"24","nombre":"Santa Elena"},
];

export const CANTONES_EC = [
  {"dpa":"0101","provincia_dpa":"01","nombre":"Cuenca"},
  {"dpa":"0102","provincia_dpa":"01","nombre":"Girón"},
  {"dpa":"0103","provincia_dpa":"01","nombre":"Gualaceo"},
  {"dpa":"0104","provincia_dpa":"01","nombre":"Nabón"},
  {"dpa":"0105","provincia_dpa":"01","nombre":"Paute"},
  {"dpa":"0106","provincia_dpa":"01","nombre":"Pucara"},
  {"dpa":"0107","provincia_dpa":"01","nombre":"San Fernando"},
  {"dpa":"0108","provincia_dpa":"01","nombre":"Santa Isabel"},
  {"dpa":"0109","provincia_dpa":"01","nombre":"Sígsig"},
  {"dpa":"0110","provincia_dpa":"01","nombre":"Oña"},
  {"dpa":"0111","provincia_dpa":"01","nombre":"Chordeleg"},
  {"dpa":"0112","provincia_dpa":"01","nombre":"El Pan"},
  {"dpa":"0113","provincia_dpa":"01","nombre":"Sevilla De Oro"},
  {"dpa":"0114","provincia_dpa":"01","nombre":"Guachapala"},
  {"dpa":"0115","provincia_dpa":"01","nombre":"Camilo Ponce Enríquez"},
  {"dpa":"0201","provincia_dpa":"02","nombre":"Guaranda"},
  {"dpa":"0202","provincia_dpa":"02","nombre":"Chillanes"},
  {"dpa":"0203","provincia_dpa":"02","nombre":"Chimbo"},
  {"dpa":"0204","provincia_dpa":"02","nombre":"Echeandía"},
  {"dpa":"0205","provincia_dpa":"02","nombre":"San Miguel"},
  {"dpa":"0206","provincia_dpa":"02","nombre":"Caluma"},
  {"dpa":"0207","provincia_dpa":"02","nombre":"Las Naves"},
  {"dpa":"0301","provincia_dpa":"03","nombre":"Azogues"},
  {"dpa":"0302","provincia_dpa":"03","nombre":"Biblián"},
  {"dpa":"0303","provincia_dpa":"03","nombre":"Cañar"},
  {"dpa":"0304","provincia_dpa":"03","nombre":"La Troncal"},
  {"dpa":"0305","provincia_dpa":"03","nombre":"El Tambo"},
  {"dpa":"0306","provincia_dpa":"03","nombre":"Déleg"},
  {"dpa":"0307","provincia_dpa":"03","nombre":"Suscal"},
  {"dpa":"0401","provincia_dpa":"04","nombre":"Tulcán"},
  {"dpa":"0402","provincia_dpa":"04","nombre":"Bolívar"},
  {"dpa":"0403","provincia_dpa":"04","nombre":"Espejo"},
  {"dpa":"0404","provincia_dpa":"04","nombre":"Mira"},
  {"dpa":"0405","provincia_dpa":"04","nombre":"Montúfar"},
  {"dpa":"0406","provincia_dpa":"04","nombre":"San Pedro De Huaca"},
  {"dpa":"0501","provincia_dpa":"05","nombre":"Latacunga"},
  {"dpa":"0502","provincia_dpa":"05","nombre":"La Maná"},
  {"dpa":"0503","provincia_dpa":"05","nombre":"Pangua"},
  {"dpa":"0504","provincia_dpa":"05","nombre":"Pujili"},
  {"dpa":"0505","provincia_dpa":"05","nombre":"Salcedo"},
  {"dpa":"0506","provincia_dpa":"05","nombre":"Saquisilí"},
  {"dpa":"0507","provincia_dpa":"05","nombre":"Sigchos"},
  {"dpa":"0601","provincia_dpa":"06","nombre":"Riobamba"},
  {"dpa":"0602","provincia_dpa":"06","nombre":"Alausi"},
  {"dpa":"0603","provincia_dpa":"06","nombre":"Colta"},
  {"dpa":"0604","provincia_dpa":"06","nombre":"Chambo"},
  {"dpa":"0605","provincia_dpa":"06","nombre":"Chunchi"},
  {"dpa":"0606","provincia_dpa":"06","nombre":"Guamote"},
  {"dpa":"0607","provincia_dpa":"06","nombre":"Guano"},
  {"dpa":"0608","provincia_dpa":"06","nombre":"Pallatanga"},
  {"dpa":"0609","provincia_dpa":"06","nombre":"Penipe"},
  {"dpa":"0610","provincia_dpa":"06","nombre":"Cumandá"},
  {"dpa":"0701","provincia_dpa":"07","nombre":"Machala"},
  {"dpa":"0702","provincia_dpa":"07","nombre":"Arenillas"},
  {"dpa":"0703","provincia_dpa":"07","nombre":"Atahualpa"},
  {"dpa":"0704","provincia_dpa":"07","nombre":"Balsas"},
  {"dpa":"0705","provincia_dpa":"07","nombre":"Chilla"},
  {"dpa":"0706","provincia_dpa":"07","nombre":"El Guabo"},
  {"dpa":"0707","provincia_dpa":"07","nombre":"Huaquillas"},
  {"dpa":"0708","provincia_dpa":"07","nombre":"Marcabelí"},
  {"dpa":"0709","provincia_dpa":"07","nombre":"Pasaje"},
  {"dpa":"0710","provincia_dpa":"07","nombre":"Piñas"},
  {"dpa":"0711","provincia_dpa":"07","nombre":"Portovelo"},
  {"dpa":"0712","provincia_dpa":"07","nombre":"Santa Rosa"},
  {"dpa":"0713","provincia_dpa":"07","nombre":"Zaruma"},
  {"dpa":"0714","provincia_dpa":"07","nombre":"Las Lajas"},
  {"dpa":"0801","provincia_dpa":"08","nombre":"Esmeraldas"},
  {"dpa":"0802","provincia_dpa":"08","nombre":"Eloy Alfaro"},
  {"dpa":"0803","provincia_dpa":"08","nombre":"Muisne"},
  {"dpa":"0804","provincia_dpa":"08","nombre":"Quinindé"},
  {"dpa":"0805","provincia_dpa":"08","nombre":"San Lorenzo"},
  {"dpa":"0806","provincia_dpa":"08","nombre":"Atacames"},
  {"dpa":"0807","provincia_dpa":"08","nombre":"Ríoverde"},
  {"dpa":"0901","provincia_dpa":"09","nombre":"Guayaquil"},
  {"dpa":"0902","provincia_dpa":"09","nombre":"Alfredo Baquerizo Moreno"},
  {"dpa":"0903","provincia_dpa":"09","nombre":"Balao"},
  {"dpa":"0904","provincia_dpa":"09","nombre":"Balzar"},
  {"dpa":"0905","provincia_dpa":"09","nombre":"Colimes"},
  {"dpa":"0906","provincia_dpa":"09","nombre":"Daule"},
  {"dpa":"0907","provincia_dpa":"09","nombre":"Durán"},
  {"dpa":"0908","provincia_dpa":"09","nombre":"El Empalme"},
  {"dpa":"0909","provincia_dpa":"09","nombre":"El Triunfo"},
  {"dpa":"0910","provincia_dpa":"09","nombre":"Milagro"},
  {"dpa":"0911","provincia_dpa":"09","nombre":"Naranjal"},
  {"dpa":"0912","provincia_dpa":"09","nombre":"Naranjito"},
  {"dpa":"0913","provincia_dpa":"09","nombre":"Palestina"},
  {"dpa":"0914","provincia_dpa":"09","nombre":"Pedro Carbo"},
  {"dpa":"0916","provincia_dpa":"09","nombre":"Samborondón"},
  {"dpa":"0918","provincia_dpa":"09","nombre":"Santa Lucía"},
  {"dpa":"0919","provincia_dpa":"09","nombre":"Salitre"},
  {"dpa":"0920","provincia_dpa":"09","nombre":"San Jacinto De Yaguachi"},
  {"dpa":"0921","provincia_dpa":"09","nombre":"Playas"},
  {"dpa":"0922","provincia_dpa":"09","nombre":"Simón Bolívar"},
  {"dpa":"0923","provincia_dpa":"09","nombre":"Coronel Marcelino Maridueña"},
  {"dpa":"0924","provincia_dpa":"09","nombre":"Lomas De Sargentillo"},
  {"dpa":"0925","provincia_dpa":"09","nombre":"Nobol"},
  {"dpa":"0927","provincia_dpa":"09","nombre":"General Antonio Elizalde"},
  {"dpa":"0928","provincia_dpa":"09","nombre":"Isidro Ayora"},
  {"dpa":"1001","provincia_dpa":"10","nombre":"Ibarra"},
  {"dpa":"1002","provincia_dpa":"10","nombre":"Antonio Ante"},
  {"dpa":"1003","provincia_dpa":"10","nombre":"Cotacachi"},
  {"dpa":"1004","provincia_dpa":"10","nombre":"Otavalo"},
  {"dpa":"1005","provincia_dpa":"10","nombre":"Pimampiro"},
  {"dpa":"1006","provincia_dpa":"10","nombre":"San Miguel De Urcuquí"},
  {"dpa":"1101","provincia_dpa":"11","nombre":"Loja"},
  {"dpa":"1102","provincia_dpa":"11","nombre":"Calvas"},
  {"dpa":"1103","provincia_dpa":"11","nombre":"Catamayo"},
  {"dpa":"1104","provincia_dpa":"11","nombre":"Celica"},
  {"dpa":"1105","provincia_dpa":"11","nombre":"Chaguarpamba"},
  {"dpa":"1106","provincia_dpa":"11","nombre":"Espíndola"},
  {"dpa":"1107","provincia_dpa":"11","nombre":"Gonzanamá"},
  {"dpa":"1108","provincia_dpa":"11","nombre":"Macará"},
  {"dpa":"1109","provincia_dpa":"11","nombre":"Paltas"},
  {"dpa":"1110","provincia_dpa":"11","nombre":"Puyango"},
  {"dpa":"1111","provincia_dpa":"11","nombre":"Saraguro"},
  {"dpa":"1112","provincia_dpa":"11","nombre":"Sozoranga"},
  {"dpa":"1113","provincia_dpa":"11","nombre":"Zapotillo"},
  {"dpa":"1114","provincia_dpa":"11","nombre":"Pindal"},
  {"dpa":"1115","provincia_dpa":"11","nombre":"Quilanga"},
  {"dpa":"1116","provincia_dpa":"11","nombre":"Olmedo"},
  {"dpa":"1201","provincia_dpa":"12","nombre":"Babahoyo"},
  {"dpa":"1202","provincia_dpa":"12","nombre":"Baba"},
  {"dpa":"1203","provincia_dpa":"12","nombre":"Montalvo"},
  {"dpa":"1204","provincia_dpa":"12","nombre":"Puebloviejo"},
  {"dpa":"1205","provincia_dpa":"12","nombre":"Quevedo"},
  {"dpa":"1206","provincia_dpa":"12","nombre":"Urdaneta"},
  {"dpa":"1207","provincia_dpa":"12","nombre":"Ventanas"},
  {"dpa":"1208","provincia_dpa":"12","nombre":"Vinces"},
  {"dpa":"1209","provincia_dpa":"12","nombre":"Palenque"},
  {"dpa":"1210","provincia_dpa":"12","nombre":"Buena Fé"},
  {"dpa":"1211","provincia_dpa":"12","nombre":"Valencia"},
  {"dpa":"1212","provincia_dpa":"12","nombre":"Mocache"},
  {"dpa":"1213","provincia_dpa":"12","nombre":"Quinsaloma"},
  {"dpa":"1301","provincia_dpa":"13","nombre":"Portoviejo"},
  {"dpa":"1302","provincia_dpa":"13","nombre":"Bolívar"},
  {"dpa":"1303","provincia_dpa":"13","nombre":"Chone"},
  {"dpa":"1304","provincia_dpa":"13","nombre":"El Carmen"},
  {"dpa":"1305","provincia_dpa":"13","nombre":"Flavio Alfaro"},
  {"dpa":"1306","provincia_dpa":"13","nombre":"Jipijapa"},
  {"dpa":"1307","provincia_dpa":"13","nombre":"Junín"},
  {"dpa":"1308","provincia_dpa":"13","nombre":"Manta"},
  {"dpa":"1309","provincia_dpa":"13","nombre":"Montecristi"},
  {"dpa":"1310","provincia_dpa":"13","nombre":"Paján"},
  {"dpa":"1311","provincia_dpa":"13","nombre":"Pichincha"},
  {"dpa":"1312","provincia_dpa":"13","nombre":"Rocafuerte"},
  {"dpa":"1313","provincia_dpa":"13","nombre":"Santa Ana"},
  {"dpa":"1314","provincia_dpa":"13","nombre":"Sucre"},
  {"dpa":"1315","provincia_dpa":"13","nombre":"Tosagua"},
  {"dpa":"1316","provincia_dpa":"13","nombre":"24 De Mayo"},
  {"dpa":"1317","provincia_dpa":"13","nombre":"Pedernales"},
  {"dpa":"1318","provincia_dpa":"13","nombre":"Olmedo"},
  {"dpa":"1319","provincia_dpa":"13","nombre":"Puerto López"},
  {"dpa":"1320","provincia_dpa":"13","nombre":"Jama"},
  {"dpa":"1321","provincia_dpa":"13","nombre":"Jaramijó"},
  {"dpa":"1322","provincia_dpa":"13","nombre":"San Vicente"},
  {"dpa":"1401","provincia_dpa":"14","nombre":"Morona"},
  {"dpa":"1402","provincia_dpa":"14","nombre":"Gualaquiza"},
  {"dpa":"1403","provincia_dpa":"14","nombre":"Limón Indanza"},
  {"dpa":"1404","provincia_dpa":"14","nombre":"Palora"},
  {"dpa":"1405","provincia_dpa":"14","nombre":"Santiago"},
  {"dpa":"1406","provincia_dpa":"14","nombre":"Sucúa"},
  {"dpa":"1407","provincia_dpa":"14","nombre":"Huamboya"},
  {"dpa":"1408","provincia_dpa":"14","nombre":"San Juan Bosco"},
  {"dpa":"1409","provincia_dpa":"14","nombre":"Taisha"},
  {"dpa":"1410","provincia_dpa":"14","nombre":"Logroño"},
  {"dpa":"1411","provincia_dpa":"14","nombre":"Pablo Sexto"},
  {"dpa":"1412","provincia_dpa":"14","nombre":"Tiwintza"},
  {"dpa":"1413","provincia_dpa":"14","nombre":"Sevilla Don Bosco"},
  {"dpa":"1501","provincia_dpa":"15","nombre":"Tena"},
  {"dpa":"1503","provincia_dpa":"15","nombre":"Archidona"},
  {"dpa":"1504","provincia_dpa":"15","nombre":"El Chaco"},
  {"dpa":"1507","provincia_dpa":"15","nombre":"Quijos"},
  {"dpa":"1509","provincia_dpa":"15","nombre":"Carlos Julio Arosemena Tola"},
  {"dpa":"1601","provincia_dpa":"16","nombre":"Pastaza"},
  {"dpa":"1602","provincia_dpa":"16","nombre":"Mera"},
  {"dpa":"1603","provincia_dpa":"16","nombre":"Santa Clara"},
  {"dpa":"1604","provincia_dpa":"16","nombre":"Arajuno"},
  {"dpa":"1701","provincia_dpa":"17","nombre":"Distrito Metropolitano De Quito"},
  {"dpa":"1702","provincia_dpa":"17","nombre":"Cayambe"},
  {"dpa":"1703","provincia_dpa":"17","nombre":"Mejia"},
  {"dpa":"1704","provincia_dpa":"17","nombre":"Pedro Moncayo"},
  {"dpa":"1705","provincia_dpa":"17","nombre":"Rumiñahui"},
  {"dpa":"1707","provincia_dpa":"17","nombre":"San Miguel De Los Bancos"},
  {"dpa":"1708","provincia_dpa":"17","nombre":"Pedro Vicente Maldonado"},
  {"dpa":"1709","provincia_dpa":"17","nombre":"Puerto Quito"},
  {"dpa":"1801","provincia_dpa":"18","nombre":"Ambato"},
  {"dpa":"1802","provincia_dpa":"18","nombre":"Baños De Agua Santa"},
  {"dpa":"1803","provincia_dpa":"18","nombre":"Cevallos"},
  {"dpa":"1804","provincia_dpa":"18","nombre":"Mocha"},
  {"dpa":"1805","provincia_dpa":"18","nombre":"Patate"},
  {"dpa":"1806","provincia_dpa":"18","nombre":"Quero"},
  {"dpa":"1807","provincia_dpa":"18","nombre":"San Pedro De Pelileo"},
  {"dpa":"1808","provincia_dpa":"18","nombre":"Santiago De Píllaro"},
  {"dpa":"1809","provincia_dpa":"18","nombre":"Tisaleo"},
  {"dpa":"1901","provincia_dpa":"19","nombre":"Zamora"},
  {"dpa":"1902","provincia_dpa":"19","nombre":"Chinchipe"},
  {"dpa":"1903","provincia_dpa":"19","nombre":"Nangaritza"},
  {"dpa":"1904","provincia_dpa":"19","nombre":"Yacuambi"},
  {"dpa":"1905","provincia_dpa":"19","nombre":"Yantzaza"},
  {"dpa":"1906","provincia_dpa":"19","nombre":"El Pangui"},
  {"dpa":"1907","provincia_dpa":"19","nombre":"Centinela Del Cóndor"},
  {"dpa":"1908","provincia_dpa":"19","nombre":"Palanda"},
  {"dpa":"1909","provincia_dpa":"19","nombre":"Paquisha"},
  {"dpa":"2001","provincia_dpa":"20","nombre":"San Cristóbal"},
  {"dpa":"2002","provincia_dpa":"20","nombre":"Isabela"},
  {"dpa":"2003","provincia_dpa":"20","nombre":"Santa Cruz"},
  {"dpa":"2101","provincia_dpa":"21","nombre":"Lago Agrio"},
  {"dpa":"2102","provincia_dpa":"21","nombre":"Gonzalo Pizarro"},
  {"dpa":"2103","provincia_dpa":"21","nombre":"Putumayo"},
  {"dpa":"2104","provincia_dpa":"21","nombre":"Shushufindi"},
  {"dpa":"2105","provincia_dpa":"21","nombre":"Sucumbíos"},
  {"dpa":"2106","provincia_dpa":"21","nombre":"Cascales"},
  {"dpa":"2107","provincia_dpa":"21","nombre":"Cuyabeno"},
  {"dpa":"2201","provincia_dpa":"22","nombre":"Francisco De Orellana"},
  {"dpa":"2202","provincia_dpa":"22","nombre":"Aguarico"},
  {"dpa":"2203","provincia_dpa":"22","nombre":"La Joya De Los Sachas"},
  {"dpa":"2204","provincia_dpa":"22","nombre":"Loreto"},
  {"dpa":"2301","provincia_dpa":"23","nombre":"Santo Domingo"},
  {"dpa":"2401","provincia_dpa":"24","nombre":"Santa Elena"},
  {"dpa":"2402","provincia_dpa":"24","nombre":"La Libertad"},
  {"dpa":"2403","provincia_dpa":"24","nombre":"Salinas"},
];

export const OPERADORAS = [
  {"codigo":"CLARO","nombre":"Claro","pais_iso":"EC"},
  {"codigo":"MOVISTAR","nombre":"Movistar","pais_iso":"EC"},
  {"codigo":"CNT","nombre":"CNT","pais_iso":"EC"},
  {"codigo":"TUENTI","nombre":"Tuenti","pais_iso":"EC"},
  {"codigo":"OTRA","nombre":"Otra","pais_iso":null},
];
