sonar.projectKey=deasy
sonar.projectName=Deasy (PUCESE)
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src,signer,scripts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/venv/**,**/public/**,**/*.min.js,docs/**,**/pnpm-lock.yaml,**/package-lock.json,backend/services/system/seeds/**

sonar.tests=
sonar.sourceEncoding=UTF-8

sonar.javascript.exclusions=**/node_modules/**
sonar.python.version=3.11
