key: "investigación/integración/artículos-académicos/revistas/ieee"
export_id: "tpl_investigación_integración_artículos_académicos_revistas_ieee"
name: "IEEE Template"
domain: investigacion
repository_stage: published
version: 1.0.0
storage_version: v0001
modes:
  general:
    latex:
      path: "modes/general/latex/src"
origins:
  - "Sharepoint/EQUIPO EIS - Documentos/DCC/ITI/2026/PPO2026/Investigación/Integración/Artículos Académicos/Estudiantes/Estudiante Demo Uno"
workflows:
  fill:
    required: true
    source: "artifact"
    sync_mode: "artifact_to_db"
    steps: []
  signatures:
    required: false
    source: "artifact"
    sync_mode: "artifact_to_db"
    anchors: []
    steps: []
dependencies:
  templates: []
  data: []
