name: deasy-qa

services:
  nginx-proxy:
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"

  mariadb:
    env_file:
      - .env.qa
    ports:
      - "13306:3306"

  mongodb:
    env_file:
      - .env.qa
    ports:
      - "12717:27017"

  rabbitmq:
    env_file:
      - .env.qa
    ports:
      - "15672:5672"
      - "15673:15672"

  emqx:
    env_file:
      - .env.qa
    ports:
      - "11883:1883"
      - "18084:18083"

  minio:
    env_file:
      - .env.qa
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

  minio-bootstrap:
    env_file:
      - .env.qa

  minio-publish-seeds:
    env_file:
      - .env.qa

  minio-publish:
    env_file:
      - .env.qa

  backend:
    image: ${IMAGE_REGISTRY}/${BACKEND_IMAGE_REPOSITORY}:${BACKEND_IMAGE_TAG}
    pull_policy: always
    env_file:
      - .env.qa
  storage-uploader:
    image: ${IMAGE_REGISTRY}/${BACKEND_IMAGE_REPOSITORY}:${BACKEND_IMAGE_TAG}
    pull_policy: always
    env_file:
      - .env.qa

  frontend:
    image: ${IMAGE_REGISTRY}/${FRONTEND_IMAGE_REPOSITORY}:${FRONTEND_IMAGE_TAG}
    pull_policy: always
    env_file:
      - .env.qa

  signer:
    image: ${IMAGE_REGISTRY}/${SIGNER_IMAGE_REPOSITORY}:${SIGNER_IMAGE_TAG}
    pull_policy: always
    env_file:
      - .env.qa
    ports:
      - "14000:4000"

  analytics:
    image: ${IMAGE_REGISTRY}/${ANALYTICS_IMAGE_REPOSITORY}:${ANALYTICS_IMAGE_TAG}
    pull_policy: always
    env_file:
      - .env.qa

volumes:
  mariadb_data:
    name: deasy_qa_mariadb_data
  mongodb_data:
    name: deasy_qa_mongodb_data
  rabbitmq_data:
    name: deasy_qa_rabbitmq_data
  emqx_data:
    name: deasy_qa_emqx_data
  emqx_log:
    name: deasy_qa_emqx_log
  minio_data:
    name: deasy_qa_minio_data
  backend_node_modules_v2:
    name: deasy_qa_backend_node_modules
  frontend_node_modules:
    name: deasy_qa_frontend_node_modules
  uploads_data:
    name: deasy_qa_uploads_data
  storage_data:
    name: deasy_qa_storage_data

networks:
  default:
    name: deasy_qa_network
