// Traductor mecánico MariaDB -> PostgreSQL DDL para deasy.
// Maneja: tipos, AUTO_INCREMENT->IDENTITY, ENUM->TEXT+CHECK, DATETIME->TIMESTAMP,
// TINYINT->SMALLINT, JSON->JSONB, LONGTEXT->TEXT, UNSIGNED (drop), ENGINE/CHARSET
// (drop), índices inline (INDEX/KEY/UNIQUE KEY -> CREATE [UNIQUE] INDEX),
// ON UPDATE CURRENT_TIMESTAMP (drop + trigger set_updated_at), ALTER ... AFTER (drop).
// NO maneja los 5 triggers de negocio (bloque DELIMITER //) — se portan a mano.

import { readFileSync, writeFileSync } from "node:fs";

const SRC = process.argv[2];
const OUT = process.argv[3];
let sql = readFileSync(SRC, "utf8");

// 1) Aislar y descartar el bloque de triggers de negocio (DELIMITER // ... DELIMITER ;)
const delimStart = sql.indexOf("DELIMITER //");
const delimEnd = sql.indexOf("DELIMITER ;");
if (delimStart !== -1 && delimEnd !== -1) {
  sql = sql.slice(0, delimStart) + sql.slice(delimEnd + "DELIMITER ;".length);
}

const lines = sql.split("\n");

// Convierte llamadas MySQL fn(args) con parseo balanceado de paréntesis.
function convertCalls(s, fn, build) {
  const re = new RegExp(`\\b${fn}\\s*\\(`, "i");
  let m;
  while ((m = re.exec(s))) {
    const start = m.index;
    const open = m.index + m[0].length - 1;
    let depth = 0;
    let i = open;
    const args = [];
    let cur = "";
    for (; i < s.length; i++) {
      const c = s[i];
      if (c === "(") { depth++; if (depth === 1) continue; }
      if (c === ")") { depth--; if (depth === 0) { args.push(cur); break; } }
      if (c === "," && depth === 1) { args.push(cur); cur = ""; continue; }
      cur += c;
    }
    s = s.slice(0, start) + build(args.map((a) => a.trim())) + s.slice(i + 1);
  }
  return s;
}

function convertFuncs(s) {
  s = convertCalls(s, "IFNULL", (a) => `COALESCE(${a.join(", ")})`);
  s = convertCalls(s, "IF", (a) => `CASE WHEN ${a[0]} THEN ${a[1]} ELSE ${a[2]} END`);
  return s;
}

// Transforma una línea de columna/constraint (tipos, enum, auto_increment...).
function transformColumn(text) {
  let t = text;
  // Columnas generadas: MariaDB `col ... AS (expr) PERSISTENT` -> PG GENERATED ... STORED.
  if (/\bAS\s*\(/i.test(t) && /\bPERSISTENT\b/i.test(t)) {
    t = convertFuncs(t);
    t = t.replace(/\bAS\s*\(/i, "GENERATED ALWAYS AS (");
    t = t.replace(/\bPERSISTENT\b/i, "STORED");
  }
  t = t.replace(/\s+UNSIGNED\b/gi, "");
  t = t.replace(/\bTINYINT\s*\(\s*\d+\s*\)/gi, "SMALLINT").replace(/\bTINYINT\b/gi, "SMALLINT");
  t = t.replace(/\bDATETIME\b/gi, "TIMESTAMP");
  t = t.replace(/\b(LONGTEXT|MEDIUMTEXT)\b/gi, "TEXT");
  t = t.replace(/\bJSON\b/gi, "JSONB");
  // AUTO_INCREMENT -> IDENTITY (para INT/BIGINT/SMALLINT)
  t = t.replace(/\b(INT|BIGINT|SMALLINT)\s+AUTO_INCREMENT\b/gi, "$1 GENERATED BY DEFAULT AS IDENTITY");
  t = t.replace(/\s+AUTO_INCREMENT\b/gi, "");
  // ENUM('a','b') -> TEXT CHECK (col IN ('a','b'))
  t = t.replace(/(\w+)\s+ENUM\s*\(([^)]*)\)/gi, "$1 TEXT CHECK ($1 IN ($2))");
  // ON UPDATE CURRENT_TIMESTAMP -> quitar (se maneja con trigger)
  t = t.replace(/\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP\b/gi, "");
  return t;
}

// Clasifica un item del cuerpo. Devuelve {kind, ...}.
function classifyItem(itemRaw) {
  const item = itemRaw.trim().replace(/,\s*$/, "");
  const idx = item.match(/^(UNIQUE\s+KEY|FULLTEXT\s+KEY|KEY|INDEX)\s+(?:([A-Za-z_][\w]*)\s*)?\((.+)\)$/i);
  if (idx) {
    return { kind: "index", unique: /UNIQUE/i.test(idx[1]), name: idx[2] || null, cols: idx[3].trim() };
  }
  return { kind: "col", text: transformColumn(item) };
}

const out = [];
out.push("-- Schema PostgreSQL de deasy (portado desde mariadb_schema.sql).");
out.push("-- Generado mecánicamente + triggers de negocio portados a mano al final.\n");
out.push(`CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;\n`);

// Parte el cuerpo de una tabla en items por comas de nivel superior
// (respeta paréntesis y strings), tolerando definiciones multi-línea.
function splitItems(body) {
  const items = [];
  let depth = 0;
  let cur = "";
  let inS = false;
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (inS) {
      cur += c;
      if (c === "'") { if (body[i + 1] === "'") { cur += body[++i]; continue; } inS = false; }
      continue;
    }
    if (c === "'") { inS = true; cur += c; continue; }
    if (c === "(") { depth++; cur += c; continue; }
    if (c === ")") { depth--; cur += c; continue; }
    if (c === "," && depth === 0) { items.push(cur); cur = ""; continue; }
    cur += c;
  }
  if (cur.trim()) items.push(cur);
  return items.map((s) => s.replace(/\s+/g, " ").trim()).filter(Boolean);
}

let inTable = false;
let tableName = null;
let bodyRaw = "";

const flushTable = () => {
  const items = splitItems(bodyRaw);
  const bodyItems = [];
  const indexStmts = [];
  const hasUpdatedAt = /ON\s+UPDATE\s+CURRENT_TIMESTAMP/i.test(bodyRaw);

  for (const item of items) {
    const cls = classifyItem(item);
    if (cls.kind === "index") {
      const name = cls.name || `${tableName}_${cls.cols.replace(/[^A-Za-z0-9]+/g, "_")}_idx`;
      indexStmts.push(
        `CREATE ${cls.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${name} ON ${tableName} (${cls.cols});`
      );
    } else {
      bodyItems.push(cls.text);
    }
  }

  out.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);
  out.push(bodyItems.map((c) => `  ${c}`).join(",\n"));
  out.push(");");
  for (const ix of indexStmts) out.push(ix);
  if (hasUpdatedAt) {
    out.push(
      `CREATE TRIGGER trg_${tableName}_set_updated_at BEFORE UPDATE ON ${tableName} ` +
        `FOR EACH ROW EXECUTE FUNCTION set_updated_at();`
    );
  }
  out.push("");
  inTable = false;
  tableName = null;
  bodyRaw = "";
};

for (let raw of lines) {
  // Quita comentarios de línea (-- ...) para no contaminar el parseo del cuerpo.
  const line = raw.replace(/--.*$/, "");
  const trimmed = line.trim();

  if (!inTable) {
    const m = trimmed.match(/^CREATE TABLE (?:IF NOT EXISTS )?([A-Za-z_][\w]*)\s*\(\s*$/i);
    if (m) {
      inTable = true;
      tableName = m[1];
      bodyRaw = "";
      continue;
    }
    // Fuera de tabla: ALTER (quitar AFTER), CAST(... AS UNSIGNED) de la vista, resto tal cual.
    out.push(raw.replace(/\s+AFTER\s+[A-Za-z_][\w]*/gi, "").replace(/\bAS\s+UNSIGNED\b/gi, "AS INTEGER"));
    continue;
  }

  // Dentro de tabla: acumular hasta la línea de cierre ") ENGINE=..." / ");".
  if (/^\)/.test(trimmed)) {
    flushTable();
    continue;
  }
  bodyRaw += " " + line;
}

let outText = out.join("\n");

// Seeds upsert: ON DUPLICATE KEY UPDATE col = VALUES(col)
//            -> ON CONFLICT (<target>) DO UPDATE SET col = EXCLUDED.col
outText = outText.replace(/=\s*VALUES\(\s*(\w+)\s*\)/gi, "= EXCLUDED.$1");
const CONFLICT_TARGET = { term_types: "id", signature_statuses: "code", signature_request_statuses: "code" };
for (const [table, target] of Object.entries(CONFLICT_TARGET)) {
  const re = new RegExp(`(INSERT INTO ${table}\\b[\\s\\S]*?)ON DUPLICATE KEY UPDATE`, "i");
  outText = outText.replace(re, `$1ON CONFLICT (${target}) DO UPDATE SET`);
}

writeFileSync(OUT, outText);
console.log(`OK -> ${OUT} (${out.length} líneas)`);
