-- Diccionario de tildes para la prosa de `arquitectura-deasy.tex`.
--
-- El original esta escrito ENTERO sin tildes ("Autenticacion", "peticion", "pagina") mientras
-- el resto del sitio si las lleva. No es un fallo de conversion: es como se escribio el .tex.
--
-- ── Por que un diccionario y no una regla ─────────────────────────────────────────────
-- Una regla del tipo `-cion -> -ción` parece suficiente y NO lo es: `createTemplateArtifactVersion`
-- casa con ese patron y quedaria destrozado. Con lista explicita, lo que no esta en la lista
-- no se toca.
--
-- ── Que NO esta aqui, a proposito ─────────────────────────────────────────────────────
-- Las palabras cuya tilde depende del contexto: mas/mas, esta/esta, aun/aun, si/si, seria/seria.
-- Acentuarlas a ciegas introduce errores de lengua, que es peor que no acentuar.
--
-- Ojo: `cedula` y `version` son ademas nombres de columna del esquema. Estan aqui porque el
-- filtro solo toca nodos `Str` (prosa) y jamas `Code`, y porque se comprobo que las 12
-- apariciones desnudas del documento son todas prosa ("comparando por cedula", "la version
-- vigente"), no celdas con nombres de columna.
--
-- Generado desde el intermedio; revisar si el .tex cambia.
return {
  ["accion"] = "acción",
  ["Ademas"] = "Además",
  ["ademas"] = "además",
  ["administracion"] = "administración",
  ["ambito"] = "ámbito",
  ["analisis"] = "análisis",
  ["anos"] = "años",
  ["aplicacion"] = "aplicación",
  ["aprobacion"] = "aprobación",
  ["aqui"] = "aquí",
  ["Aqui"] = "Aquí",
  ["arbol"] = "árbol",
  ["Asi"] = "Así",
  ["asi"] = "así",
  ["Autenticacion"] = "Autenticación",
  ["autenticacion"] = "autenticación",
  ["automatica"] = "automática",
  ["automaticamente"] = "automáticamente",
  ["automatico"] = "automático",
  ["Autorizacion"] = "Autorización",
  ["autorizacion"] = "autorización",
  ["Caracterizacion"] = "Caracterización",
  ["caracterizacion"] = "caracterización",
  ["Cedula"] = "Cédula",
  ["cedula"] = "cédula",
  ["cedulas"] = "cédulas",
  ["Codigo"] = "Código",
  ["codigo"] = "código",
  ["codigos"] = "códigos",
  ["comunicacion"] = "comunicación",
  ["Configuracion"] = "Configuración",
  ["configuracion"] = "configuración",
  ["confirmacion"] = "confirmación",
  ["confusion"] = "confusión",
  ["contratacion"] = "contratación",
  ["correccion"] = "corrección",
  ["critico"] = "crítico",
  ["dano"] = "daño",
  ["deberia"] = "debería",
  ["Decision"] = "Decisión",
  ["decision"] = "decisión",
  ["definicion"] = "definición",
  ["demostracion"] = "demostración",
  ["despues"] = "después",
  ["documentacion"] = "documentación",
  ["ejecucion"] = "ejecución",
  ["emision"] = "emisión",
  ["Estan"] = "Están",
  ["estan"] = "están",
  ["estatica"] = "estática",
  ["estatico"] = "estático",
  ["Excepcion"] = "Excepción",
  ["excepcion"] = "excepción",
  ["explicacion"] = "explicación",
  ["explicita"] = "explícita",
  ["explicitas"] = "explícitas",
  ["explicito"] = "explícito",
  ["explicitos"] = "explícitos",
  ["extraccion"] = "extracción",
  ["fragil"] = "frágil",
  ["Funcion"] = "Función",
  ["funcion"] = "función",
  ["generico"] = "genérico",
  ["Habia"] = "Había",
  ["habria"] = "habría",
  ["hacia"] = "hacía",
  ["historica"] = "histórica",
  ["implementacion"] = "implementación",
  ["indentacion"] = "indentación",
  ["indice"] = "índice",
  ["Ingenieria"] = "Ingeniería",
  ["instalacion"] = "instalación",
  ["Instanciacion"] = "Instanciación",
  ["integracion"] = "integración",
  ["invalido"] = "inválido",
  ["Investigacion"] = "Investigación",
  ["investigacion"] = "investigación",
  ["iteracion"] = "iteración",
  ["jerarquia"] = "jerarquía",
  ["justificacion"] = "justificación",
  ["linea"] = "línea",
  ["lineas"] = "líneas",
  ["Lineas"] = "Líneas",
  ["logica"] = "lógica",
  ["maduracion"] = "maduración",
  ["medicion"] = "medición",
  ["metodo"] = "método",
  ["metodos"] = "métodos",
  ["migracion"] = "migración",
  ["minimo"] = "mínimo",
  ["multiples"] = "múltiples",
  ["navegacion"] = "navegación",
  ["negociacion"] = "negociación",
  ["numeros"] = "números",
  ["Organizacion"] = "Organización",
  ["pagina"] = "página",
  ["paginas"] = "páginas",
  ["parametros"] = "parámetros",
  ["peticion"] = "petición",
  ["podria"] = "podría",
  ["politica"] = "política",
  ["politicas"] = "políticas",
  ["posicion"] = "posición",
  ["produccion"] = "producción",
  ["Produccion"] = "Producción",
  ["proposito"] = "propósito",
  ["Publica"] = "Pública",
  ["publica"] = "pública",
  ["publicacion"] = "publicación",
  ["publicas"] = "públicas",
  ["publico"] = "público",
  ["publicos"] = "públicos",
  ["redireccion"] = "redirección",
  ["resolucion"] = "resolución",
  ["seccion"] = "sección",
  ["segun"] = "según",
  ["Separacion"] = "Separación",
  ["separacion"] = "separación",
  ["sesion"] = "sesión",
  ["sintactico"] = "sintáctico",
  ["solucion"] = "solución",
  ["suscripcion"] = "suscripción",
  ["Tambien"] = "También",
  ["tambien"] = "también",
  ["tendria"] = "tendría",
  ["tenia"] = "tenía",
  ["Traduccion"] = "Traducción",
  ["transaccion"] = "transacción",
  ["ubicacion"] = "ubicación",
  ["ultima"] = "última",
  ["ultimo"] = "último",
  ["unica"] = "única",
  ["unico"] = "único",
  ["unicos"] = "únicos",
  ["Valida"] = "Válida",
  ["valida"] = "válida",
  ["Validacion"] = "Validación",
  ["validacion"] = "validación",
  ["valido"] = "válido",
  ["validos"] = "válidos",
  ["variacion"] = "variación",
  ["version"] = "versión",
  ["via"] = "vía",
  ["vinculacion"] = "vinculación",
  ["violacion"] = "violación",
}
